version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/authnginx/htpasswd:/etc/nginx/authnginx/htpasswd